---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-argocd-config'
      annotations:
        argocd.argoproj.io/sync-wave: '3'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: argocd
      sources:
        - repoURL: https://github.com/mixxor/argocd-cluster-essentials.git
          targetRevision: main
          path: manifests/argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
