---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak-config-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-keycloak-config-operator'
      annotations:
        argocd.argoproj.io/sync-wave: '1'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: keycloak-operator
      sources:
        - repoURL: https://github.com/mixxor/argocd-cluster-essentials.git
          targetRevision: main
          ref: values
        - repoURL: https://epam.github.io/edp-helm-charts/stable
          chart: keycloak-operator
          targetRevision: 1.31.1
          helm:
            releaseName: keycloak-config-operator
            valueFiles: [$values/values/keycloak-config-operator/values-basic.yaml]
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
