---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-metrics-server'
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: kube-system
      sources:
        - repoURL: https://github.com/mixxor/argocd-cluster-essentials.git
          targetRevision: main
          ref: values
        - repoURL: https://kubernetes-sigs.github.io/metrics-server
          chart: metrics-server
          targetRevision: 3.12.2
          helm:
            releaseName: metrics-server
            valueFiles: [$values/values/metrics-server/values-basic.yaml]
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
