---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
    - name: stress
      image: lorel/docker-stress-ng
      args:
        - --cpu
        - '4'
        - --cpu-method
        - matrixprod
        - --metrics-brief
        - --timeout
        - 60s
  restartPolicy: Never
